name: backend
description: Darts_application client backend, used for the models and logic.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  supabase_flutter: ^2.5.1
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  provider: ^6.1.2
  mockito: ^5.4.4
  # path: ^1.8.0
  darts_application:
    path: ../frontend

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
