name: backend
description: Darts_application client backend, used for the models and logic.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  build_runner: ^2.1.5
  mobx_codegen: ^2.0.1
  mobx: ^2.3.3+2
  supabase_flutter: ^2.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
