
SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";

COMMENT ON SCHEMA "public" IS 'standard public schema';

CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";

CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";

CREATE TYPE "public"."scope" AS ENUM (
    'global',
    'club'
);

ALTER TYPE "public"."scope" OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";

CREATE TABLE IF NOT EXISTS "public"."avatar" (
    "id" bigint NOT NULL,
    "url" "text" NOT NULL
);

ALTER TABLE "public"."avatar" OWNER TO "postgres";

ALTER TABLE "public"."avatar" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."avatar_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."club" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "address" "text" NOT NULL,
    "postal_code" "text" NOT NULL,
    "city" "text" NOT NULL,
    "owner_id" "uuid" DEFAULT "auth"."uid"(),
    "banner_image_url" "text" DEFAULT 'https://uasfeuipbeokslhkvtmq.supabase.co/storage/v1/object/public/club_banners/defaultbanner.svg'::"text" NOT NULL
);

ALTER TABLE "public"."club" OWNER TO "postgres";

ALTER TABLE "public"."club" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."club_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."club_post" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "image_url" "text",
    "body" "text" NOT NULL,
    "club_id" bigint NOT NULL
);

ALTER TABLE "public"."club_post" OWNER TO "postgres";

ALTER TABLE "public"."club_post" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."club_post_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."club_role" (
    "id" bigint NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL
);

ALTER TABLE "public"."club_role" OWNER TO "postgres";

ALTER TABLE "public"."club_role" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."club_role_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."club_role_permission" (
    "club_role_id" bigint NOT NULL,
    "permission_id" bigint NOT NULL
);

ALTER TABLE "public"."club_role_permission" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."competition" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "club_id" bigint
);

ALTER TABLE "public"."competition" OWNER TO "postgres";

ALTER TABLE "public"."competition" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."competition_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."competition_match" (
    "competition_id" bigint NOT NULL,
    "match_id" bigint NOT NULL
);

ALTER TABLE "public"."competition_match" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."leg" (
    "id" bigint NOT NULL,
    "winner_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "set_id" bigint NOT NULL
);

ALTER TABLE "public"."leg" OWNER TO "postgres";

ALTER TABLE "public"."leg" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."leg_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."match" (
    "id" bigint NOT NULL,
    "player_1_id" "uuid",
    "player_2_id" "uuid",
    "date" timestamp with time zone,
    "location" "text" DEFAULT ''::"text",
    "set_target" bigint DEFAULT '1'::bigint NOT NULL,
    "leg_target" bigint DEFAULT '1'::bigint NOT NULL,
    "starting_score" bigint DEFAULT '501'::bigint NOT NULL,
    "winner_id" "uuid"
);

ALTER TABLE "public"."match" OWNER TO "postgres";

ALTER TABLE "public"."match" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."match_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."permission" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "description" "text" NOT NULL,
    "scope" "public"."scope" DEFAULT 'global'::"public"."scope" NOT NULL
);

ALTER TABLE "public"."permission" OWNER TO "postgres";

ALTER TABLE "public"."permission" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."permission_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."role" (
    "id" bigint NOT NULL,
    "name" "text" DEFAULT ''::"text" NOT NULL
);

ALTER TABLE "public"."role" OWNER TO "postgres";

ALTER TABLE "public"."role" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."role_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."role_permission" (
    "role_id" bigint NOT NULL,
    "permission_id" bigint NOT NULL
);

ALTER TABLE "public"."role_permission" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."set" (
    "id" bigint NOT NULL,
    "winner_id" "uuid" DEFAULT "auth"."uid"(),
    "match_id" bigint NOT NULL
);

ALTER TABLE "public"."set" OWNER TO "postgres";

ALTER TABLE "public"."set" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."set_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tournament" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "location" "text" NOT NULL,
    "start_time" timestamp with time zone NOT NULL,
    "club_id" bigint
);

ALTER TABLE "public"."tournament" OWNER TO "postgres";

ALTER TABLE "public"."tournament" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tournament_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."tournament_match" (
    "tournament_id" bigint NOT NULL,
    "match_id" bigint NOT NULL
);

ALTER TABLE "public"."tournament_match" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."turn" (
    "id" bigint NOT NULL,
    "player_id" "uuid" DEFAULT "auth"."uid"(),
    "leg_id" bigint NOT NULL,
    "score" bigint NOT NULL,
    "double_attempts" integer,
    "double_hits" integer
);

ALTER TABLE "public"."turn" OWNER TO "postgres";

ALTER TABLE "public"."turn" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."turn_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE IF NOT EXISTS "public"."user" (
    "id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "avatar_id" bigint DEFAULT '1'::bigint NOT NULL
);

ALTER TABLE "public"."user" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."user_club" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "club_id" bigint NOT NULL
);

ALTER TABLE "public"."user_club" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."user_club_role" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "club_role_id" bigint NOT NULL,
    "club_id" bigint
);

ALTER TABLE "public"."user_club_role" OWNER TO "postgres";

CREATE TABLE IF NOT EXISTS "public"."user_role" (
    "user_id" "uuid" DEFAULT "auth"."uid"() NOT NULL,
    "role_id" bigint NOT NULL
);

ALTER TABLE "public"."user_role" OWNER TO "postgres";

ALTER TABLE ONLY "public"."avatar"
    ADD CONSTRAINT "avatar_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."club"
    ADD CONSTRAINT "club_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."club_post"
    ADD CONSTRAINT "club_post_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."club_role_permission"
    ADD CONSTRAINT "club_role_permission_pkey" PRIMARY KEY ("club_role_id", "permission_id");

ALTER TABLE ONLY "public"."club_role"
    ADD CONSTRAINT "club_role_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."competition_match"
    ADD CONSTRAINT "competition_match_pkey" PRIMARY KEY ("competition_id", "match_id");

ALTER TABLE ONLY "public"."competition"
    ADD CONSTRAINT "competition_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."leg"
    ADD CONSTRAINT "leg_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "match_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."permission"
    ADD CONSTRAINT "permission_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."role_permission"
    ADD CONSTRAINT "role_permission_pkey" PRIMARY KEY ("role_id", "permission_id");

ALTER TABLE ONLY "public"."role"
    ADD CONSTRAINT "role_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."set"
    ADD CONSTRAINT "set_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."tournament_match"
    ADD CONSTRAINT "tournament_match_pkey" PRIMARY KEY ("tournament_id", "match_id");

ALTER TABLE ONLY "public"."tournament"
    ADD CONSTRAINT "tournament_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."turn"
    ADD CONSTRAINT "turn_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_club"
    ADD CONSTRAINT "user_club_pkey" PRIMARY KEY ("user_id", "club_id");

ALTER TABLE ONLY "public"."user_club_role"
    ADD CONSTRAINT "user_club_role_pkey" PRIMARY KEY ("user_id", "club_role_id");

ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."user_role"
    ADD CONSTRAINT "user_role_pkey" PRIMARY KEY ("user_id", "role_id");

ALTER TABLE ONLY "public"."club"
    ADD CONSTRAINT "public_club_owner_id_fkey" FOREIGN KEY ("owner_id") REFERENCES "public"."user"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."club_post"
    ADD CONSTRAINT "public_club_post_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "public"."club"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."club_role_permission"
    ADD CONSTRAINT "public_club_role_permission_club_role_id_fkey" FOREIGN KEY ("club_role_id") REFERENCES "public"."club_role"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."club_role_permission"
    ADD CONSTRAINT "public_club_role_permission_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "public"."permission"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."competition"
    ADD CONSTRAINT "public_competition_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "public"."club"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."competition_match"
    ADD CONSTRAINT "public_competition_match_competition_id_fkey" FOREIGN KEY ("competition_id") REFERENCES "public"."competition"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."competition_match"
    ADD CONSTRAINT "public_competition_match_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "public"."match"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."leg"
    ADD CONSTRAINT "public_leg_id_fkey" FOREIGN KEY ("id") REFERENCES "public"."set"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."leg"
    ADD CONSTRAINT "public_leg_winner_id_fkey" FOREIGN KEY ("winner_id") REFERENCES "public"."user"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "public_match_player_1_id_fkey" FOREIGN KEY ("player_1_id") REFERENCES "public"."user"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "public_match_player_2_id_fkey" FOREIGN KEY ("player_2_id") REFERENCES "public"."user"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."match"
    ADD CONSTRAINT "public_match_winner_id_fkey" FOREIGN KEY ("winner_id") REFERENCES "public"."user"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."role_permission"
    ADD CONSTRAINT "public_role_permission_permission_id_fkey" FOREIGN KEY ("permission_id") REFERENCES "public"."permission"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."role_permission"
    ADD CONSTRAINT "public_role_permission_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."role"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."set"
    ADD CONSTRAINT "public_set_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "public"."match"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."set"
    ADD CONSTRAINT "public_set_winner_id_fkey" FOREIGN KEY ("winner_id") REFERENCES "public"."user"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."tournament"
    ADD CONSTRAINT "public_tournament_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "public"."club"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."tournament_match"
    ADD CONSTRAINT "public_tournament_match_match_id_fkey" FOREIGN KEY ("match_id") REFERENCES "public"."match"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."tournament_match"
    ADD CONSTRAINT "public_tournament_match_tournament_id_fkey" FOREIGN KEY ("tournament_id") REFERENCES "public"."tournament"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."turn"
    ADD CONSTRAINT "public_turn_leg_id_fkey" FOREIGN KEY ("leg_id") REFERENCES "public"."leg"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."turn"
    ADD CONSTRAINT "public_turn_player_id_fkey" FOREIGN KEY ("player_id") REFERENCES "public"."user"("id") ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "public_user_avatar_id_fkey" FOREIGN KEY ("avatar_id") REFERENCES "public"."avatar"("id") ON UPDATE CASCADE ON DELETE SET DEFAULT;

ALTER TABLE ONLY "public"."user_club"
    ADD CONSTRAINT "public_user_club_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "public"."club"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_club_role"
    ADD CONSTRAINT "public_user_club_role_club_id_fkey" FOREIGN KEY ("club_id") REFERENCES "public"."club"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_club_role"
    ADD CONSTRAINT "public_user_club_role_club_role_id_fkey" FOREIGN KEY ("club_role_id") REFERENCES "public"."club_role"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_club_role"
    ADD CONSTRAINT "public_user_club_role_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id");

ALTER TABLE ONLY "public"."user_club"
    ADD CONSTRAINT "public_user_club_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "public_user_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_role"
    ADD CONSTRAINT "public_user_role_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "public"."role"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "public"."user_role"
    ADD CONSTRAINT "public_user_role_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE "public"."avatar" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."club" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."club_post" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."club_role" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."club_role_permission" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."competition" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."competition_match" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."leg" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."match" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."permission" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."role" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."role_permission" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."set" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tournament" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."tournament_match" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."turn" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_club" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_club_role" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."user_role" ENABLE ROW LEVEL SECURITY;

ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";

GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";

GRANT ALL ON TABLE "public"."avatar" TO "anon";
GRANT ALL ON TABLE "public"."avatar" TO "authenticated";
GRANT ALL ON TABLE "public"."avatar" TO "service_role";

GRANT ALL ON SEQUENCE "public"."avatar_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."avatar_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."avatar_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."club" TO "anon";
GRANT ALL ON TABLE "public"."club" TO "authenticated";
GRANT ALL ON TABLE "public"."club" TO "service_role";

GRANT ALL ON SEQUENCE "public"."club_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."club_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."club_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."club_post" TO "anon";
GRANT ALL ON TABLE "public"."club_post" TO "authenticated";
GRANT ALL ON TABLE "public"."club_post" TO "service_role";

GRANT ALL ON SEQUENCE "public"."club_post_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."club_post_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."club_post_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."club_role" TO "anon";
GRANT ALL ON TABLE "public"."club_role" TO "authenticated";
GRANT ALL ON TABLE "public"."club_role" TO "service_role";

GRANT ALL ON SEQUENCE "public"."club_role_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."club_role_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."club_role_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."club_role_permission" TO "anon";
GRANT ALL ON TABLE "public"."club_role_permission" TO "authenticated";
GRANT ALL ON TABLE "public"."club_role_permission" TO "service_role";

GRANT ALL ON TABLE "public"."competition" TO "anon";
GRANT ALL ON TABLE "public"."competition" TO "authenticated";
GRANT ALL ON TABLE "public"."competition" TO "service_role";

GRANT ALL ON SEQUENCE "public"."competition_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."competition_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."competition_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."competition_match" TO "anon";
GRANT ALL ON TABLE "public"."competition_match" TO "authenticated";
GRANT ALL ON TABLE "public"."competition_match" TO "service_role";

GRANT ALL ON TABLE "public"."leg" TO "anon";
GRANT ALL ON TABLE "public"."leg" TO "authenticated";
GRANT ALL ON TABLE "public"."leg" TO "service_role";

GRANT ALL ON SEQUENCE "public"."leg_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."leg_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."leg_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."match" TO "anon";
GRANT ALL ON TABLE "public"."match" TO "authenticated";
GRANT ALL ON TABLE "public"."match" TO "service_role";

GRANT ALL ON SEQUENCE "public"."match_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."match_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."match_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."permission" TO "anon";
GRANT ALL ON TABLE "public"."permission" TO "authenticated";
GRANT ALL ON TABLE "public"."permission" TO "service_role";

GRANT ALL ON SEQUENCE "public"."permission_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."permission_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."permission_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."role" TO "anon";
GRANT ALL ON TABLE "public"."role" TO "authenticated";
GRANT ALL ON TABLE "public"."role" TO "service_role";

GRANT ALL ON SEQUENCE "public"."role_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."role_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."role_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."role_permission" TO "anon";
GRANT ALL ON TABLE "public"."role_permission" TO "authenticated";
GRANT ALL ON TABLE "public"."role_permission" TO "service_role";

GRANT ALL ON TABLE "public"."set" TO "anon";
GRANT ALL ON TABLE "public"."set" TO "authenticated";
GRANT ALL ON TABLE "public"."set" TO "service_role";

GRANT ALL ON SEQUENCE "public"."set_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."set_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."set_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tournament" TO "anon";
GRANT ALL ON TABLE "public"."tournament" TO "authenticated";
GRANT ALL ON TABLE "public"."tournament" TO "service_role";

GRANT ALL ON SEQUENCE "public"."tournament_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tournament_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tournament_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."tournament_match" TO "anon";
GRANT ALL ON TABLE "public"."tournament_match" TO "authenticated";
GRANT ALL ON TABLE "public"."tournament_match" TO "service_role";

GRANT ALL ON TABLE "public"."turn" TO "anon";
GRANT ALL ON TABLE "public"."turn" TO "authenticated";
GRANT ALL ON TABLE "public"."turn" TO "service_role";

GRANT ALL ON SEQUENCE "public"."turn_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."turn_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."turn_id_seq" TO "service_role";

GRANT ALL ON TABLE "public"."user" TO "anon";
GRANT ALL ON TABLE "public"."user" TO "authenticated";
GRANT ALL ON TABLE "public"."user" TO "service_role";

GRANT ALL ON TABLE "public"."user_club" TO "anon";
GRANT ALL ON TABLE "public"."user_club" TO "authenticated";
GRANT ALL ON TABLE "public"."user_club" TO "service_role";

GRANT ALL ON TABLE "public"."user_club_role" TO "anon";
GRANT ALL ON TABLE "public"."user_club_role" TO "authenticated";
GRANT ALL ON TABLE "public"."user_club_role" TO "service_role";

GRANT ALL ON TABLE "public"."user_role" TO "anon";
GRANT ALL ON TABLE "public"."user_role" TO "authenticated";
GRANT ALL ON TABLE "public"."user_role" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";

RESET ALL;
