name: Flutter Build Android APK and Windows EXE

on: 
  push: [main, test]
    tags:
      - 'v*'

jobs:
  apk:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_URL: ${{ secrets.RELEASE_SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.RELEASE_SUPABASE_ANON_KEY }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT} <<< y
      - name: Build APK
        run: |
        flutter build apk --dart-define=SUPABASE_URL=${SUPABASE_URL} --dart-define=SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}

      - uses: actions/upload-artifact@master
        with:
          name: apk
          path: build/app/outputs/flutter-apk
  
  windows:
    runs-on: windows-latest
    
    env:
      SUPABASE_URL: ${{ secrets.RELEASE_SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.RELEASE_SUPABASE_ANON_KEY }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - run: flutter config --enable-windows-desktop
      - run: flutter create .
      - run: flutter build windows --dart-define=SUPABASE_URL=${SUPABASE_URL} --dart-define=SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - uses: actions/upload-artifact@master
        with:
          name: windows
          path: build\windows\runner\Release
