name: Build and Tag Release

env:
  SUPABASE_URL: 'https://wofmpmokrotlntuqjptl.supabase.co'
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvZm1wbW9rcm90bG50dXFqcHRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTI5MTUwMjcsImV4cCI6MjAyODQ5MTAyN30.7hTbaWkxDQ-lKctP6wICrQiuPA1AwJrEFgYdVztkSdE'
  
on:
  push:
    branches:
      - main
      - test

permissions:
  contents: write  # Grant write permission to contents to push tags

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
        version: ${{ steps.get_version.outputs.VERSION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get the version from pubspec.yaml
      id: get_version
      working-directory: ./Frontend
      run: |
        VERSION=$(grep '^version: ' pubspec.yaml | sed 's/version: //' | tr -d '[:space:]')
        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
   
    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ steps.get_version.outputs.version }}
      run: |
        curl -X POST \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${GITHUB_REPOSITORY}/releases \
          -d '{
            "tag_name": "v'${VERSION}'",
            "name": "Release v'${VERSION}'",
            "body": "Release v'${VERSION}'",
            "draft": false,
            "prerelease": false
          }'


  build_android:
    needs: create-release
    runs-on: ubuntu-latest

    steps:
    - name: Echo Supabase URL
      run: echo $SUPABASE_URL

    - name: Echo Supabase Anon Key
      run: echo $SUPABASE_ANON_KEY
      
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Install dependencies
      working-directory: ./Frontend
      run: flutter pub get

    - name: Run build_runner
      run: dart run build_runner build
    
    - name: Build APK
      working-directory: ./Frontend
      run: |
        echo "Building APK with SUPABASE_URL=$SUPABASE_URL and SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY"
        flutter build apk --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY --split-per-abi
      
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: DartinMolema-${{ needs.create-release.outputs.version }}-android.zip
        directory: ./Frontend/build/app/outputs/apk/release/

    - name: Windows Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./Frontend/build/app/outputs/apk/release/DartinMolema-${{ needs.create-release.outputs.version }}-android.zip
      

  build_windows:
    needs: create-release
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'

    - name: Enable Windows desktop
      working-directory: ./Frontend
      run: flutter config --enable-windows-desktop

    - name: Install dependencies
      working-directory: ./Frontend
      run: flutter pub get

    - name: Run build_runner
      run: dart run build_runner build
      
    - name: Build Windows EXE
      working-directory: ./Frontend
      run: |
        echo "Building APK with SUPABASE_URL=$SUPABASE_URL and SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY"
        flutter build windows --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: DartinMolema-${{ needs.create-release.outputs.version }}-windows.zip
        directory: ./Frontend/build/windows/runner/Release

    - name: Windows Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./Frontend/build/windows/runner/Release/DartinMolema-${{ needs.create-release.outputs.version }}-windows.zip
      
