name: flutter-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter packages
        id: cache-flutter-sdk
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      - name: Cache Flutter action
        id: cache-flutter-action
        uses: actions/cache@v2
        with:
          path: ~/.flutter
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Cache simulator
        id: cache-simulator
        uses: actions/cache@v2
        with:
          path: ~/Library/Developer/CoreSimulator/Devices
          key: ${{ runner.os }}-simulator-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-simulator-

      - run: cd Frontend && flutter pub get
      - run: cd Frontend && flutter analyze
