name: flutter-test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

        # use flutter cache or download flutter if not cached
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'

      - run: flutter doctor

      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 14'

      - run: cd Frontend && flutter pub get
      - run: cd Frontend && flutter analyze
