name: test-backend
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
    - name: Run flutter pub get
      working-directory: ./backend
      run: flutter pub get
    - name: Run flutter test
      working-directory: ./backend
      run: flutter test
