name: test-backend
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
    - run: cd backend
    - run: ls
    - run: flutter pub get
    - run: flutter test
